version: '3.4'
services:
  nginx_my:
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
    - ./build/nginx/developer.conf:/etc/nginx/conf.d/default.conf:ro
    - project_code:/var/www/project:ro
    - ../app/pub:/var/www/project/pub:ro
    links:
    - php_my
    env_file:
    - env/nginx
  php_my:
    build:
      context: .
      dockerfile: build/php/Dockerfile
    volumes:
    - project_code:/var/www/project:rw
    - ../app/pub:/var/www/project/pub:rw
    entrypoint: /docker-entrypoint.sh
    command: sudo bash -c "/usr/sbin/sshd && /usr/local/sbin/php-fpm"
    ports:
    - "52222:22"
#    links:
#    - mysql
#    - redis
#    - rabbitmq
    env_file:
    - env/php
    - env/nginx
#    - env/mysql
#    - env/redis
#    - env/magento
#    - env/rabbitmq

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    environment:
    - node.name=es01
    - discovery.seed_hosts=es02
    - cluster.initial_master_nodes=es01,es02
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
    - 9200:9200
    volumes:
    - es_data:/usr/share/elasticsearch/data
    networks:
    - esnet

volumes:
  project_code:
    driver: local
  es_data:
    driver: local

networks:
  esnet:
